/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#fafbfc',
        foreground: '#0a1628',
        card: '#ffffff',
        'card-foreground': '#0a1628',
        popover: '#ffffff',
        'popover-foreground': '#0a1628',
        primary: '#1e3a8a',
        'primary-foreground': '#ffffff',
        secondary: '#e2e8f0',
        'secondary-foreground': '#1e3a8a',
        muted: '#f1f5f9',
        'muted-foreground': '#64748b',
        accent: '#dbeafe',
        'accent-foreground': '#1e3a8a',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: 'rgba(30, 58, 138, 0.1)',
        input: 'transparent',
        'input-background': '#f8fafc',
        'switch-background': '#cbd5e1',
        ring: '#3b82f6',
        // Marine-specific colors
        'ocean-blue': '#1e3a8a',
        'ocean-blue-light': '#3b82f6',
        'ocean-blue-dark': '#1e40af',
        aqua: '#06b6d4',
        'aqua-light': '#67e8f9',
        'sea-green': '#10b981',
        'deep-blue': '#0f172a',
        'wave-gray': '#f1f5f9',
        'foam-white': '#fefefe',
        // Sidebar
        sidebar: '#f8fafc',
        'sidebar-foreground': '#0a1628',
        'sidebar-primary': '#1e3a8a',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#f1f5f9',
        'sidebar-accent-foreground': '#1e3a8a',
        'sidebar-border': 'rgba(30, 58, 138, 0.1)',
        'sidebar-ring': '#3b82f6',
        // Custom color stops using CSS variables
        'blue-50': 'var(--color-blue-50)',
        'cyan-50': 'var(--color-cyan-50)',
      },
      fontSize: {
        base: '14px',
        sm: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
      },
      fontWeight: {
        normal: '400',
        medium: '500',
      },
      borderRadius: {
        sm: 'calc(0.625rem - 4px)',
        md: 'calc(0.625rem - 2px)',
        lg: '0.625rem',
        xl: 'calc(0.625rem + 4px)',
      },
      backgroundImage: {
        'gradient-ocean': 'linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)',
        'gradient-aqua': 'linear-gradient(135deg, #06b6d4 0%, #67e8f9 100%)',
        'gradient-to-r': 'linear-gradient(to right in oklab, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
